/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package kotlin05_gradle

import com.google.gson.Gson
import modules.Adnin

//import models.Products

class App {
    val greeting: String
        get() {
            return "Hello World!"
        }
}

class Hello() {
    companion object {
        val greeting: String
        get() {
            return "Hello"
        }
    }
}

fun main() {
    println(App().greeting)
    println(Hello.greeting)
    val gson: Gson = Gson()

    val adnin = Adnin("Adnin")
    println(adnin.name)

//    val products: Products()
}
