version: '3.5'

services:
  kotlin-restful-api:
    container_name: "kotlin-restful-api"
    image: kotlin-restful-api:0.0.1
    ports:
      - 9090:8080
    environment:
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
      DATABASE_URL: jdbc:postgresql://postgres_local:5433/kotlin