/*
 * This file was generated by the Gradle 'init' task.
 *
 * This generated file contains a sample Kotlin application project to get you started.
 * For more details take a look at the 'Building Java & JVM projects' chapter in the Gradle
 * User Manual available at https://docs.gradle.org/6.8.1/userguide/building_java_projects.html
 */

plugins {
    // Apply the org.jetbrains.kotlin.jvm Plugin to add support for Kotlin.
    id("org.jetbrains.kotlin.jvm") version "1.4.20"

    // Apply the application plugin to add support for building a CLI application in Java.
    application
}

repositories {
    // Use JCenter for resolving dependencies.
    jcenter()
    mavenCentral()
    /* dibutuhkan ketika membuat android app */
    //google()
    /* private repository*/
    //maven {
    //    url = uri("https://dl.bintray.com/bliblidotcom/maven")
    //}
}

dependencies {
    // Align versions of all Kotlin components
    implementation(platform("org.jetbrains.kotlin:kotlin-bom"))

    // Use the Kotlin JDK 8 standard library.
    implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

    // This dependency is used by the application.
    implementation("com.google.guava:guava:29.0-jre")

    // Use the Kotlin test library.
    testImplementation("org.jetbrains.kotlin:kotlin-test")

    // Use the Kotlin JUnit integration.
    testImplementation("org.jetbrains.kotlin:kotlin-test-junit")

    // menambahkan dependency
    implementation("org.jetbrains.kotlinx:kotlinx-coroutines-core:1.3.7")
    implementation("com.google.code.gson:gson:2.8.6")

    // multi module project
    implementation(project(":keyboard:lib"))
}

application {
    // Define the main class for the application.
    mainClass.set("kotlin05_gradle.AppKt")
}

/**
 * Custom Tasks
 */
tasks.register("hello") {
    doFirst {
        println("Hello")
    }
}

tasks.register("java_env") {
    /**
     * Using gradle.properties
     */
    val JAVA_ENV: String by project
    doFirst {
        println(JAVA_ENV)
    }
}